language: node_js
node_js:
  - 0.12

before_script:
  - "npm install -g gulp"
  - "npm install -g jspm"
  - "npm install -g karma"
  - "npm install"
  - "jspm registry export github"
  - "jspm install"

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script:
  - sleep 5
  - "./node_modules/.bin/karma start ./karma.conf.js --browsers Firefox --single-run"
